### ISSUE TITLE
`@?` macro does not go through `getproperty`

### ISSUE THREAD

**Issue by piever** [tkf/Maybe.jl#10]
Really nice package!

I've started playing a bit with it, and it feels nice to use. The only thing I've noticed is that, while function calls are lifted, `getproperty` is not, but it could be useful.

MWE:

```julia
julia> using Maybe

julia> m = match(r"a", "aaa")
RegexMatch("a")

julia> @? m.offset
Some(1)

julia> m = match(r"b", "aaa")

julia> @? m.offset
ERROR: type Nothing has no field offset
Stacktrace:
 [1] getproperty(::Nothing, ::Symbol) at ./Base.jl:33
 [2] top-level scope at /home/pietro/.julia/packages/Maybe/TuhZO/src/lift.jl:148
```

**Comment by tkf** [comment]
Hi, thanks for the feedback. Good to know that you find it nice to use!

I was a bit hesitant to lift the property accesses because it might generate too much code.  So I thought I'd wait for examples in which this is useful to come up in practice. I think `RegexMatch` is a good example.

---

Side notes: Your example itself can actually be worked around by putting `match` in `@?` as well

```julia
julia> @? let m = match(r"a", "bbb")
           m.offset
       end

julia> @? let m = match(r"a", "aaa")
           m.offset
       end
Some(1)
```

But I think `Union{RegexMatch,Nothing}` could be wrapped in other things like a `NamedTuple`.
